# Stage 1: Build the application
FROM gradle:8.2.0-jdk21 AS builder
WORKDIR /workspace

# Copy the project files
COPY . .

# Change directory to the product_module and build it
WORKDIR /workspace/product_module

# Build the application
RUN gradle clean build -x test

# Stage 2: Run the application
FROM openjdk:21-jdk-slim
WORKDIR /app

# Copy the built jar from the previous stage
COPY --from=builder /workspace/product_module/build/libs/productmodule-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8081
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
