# Stage 1: Build the application
FROM eclipse-temurin:21-jdk AS builder
WORKDIR /workspace

# Copy the project files to the container
COPY . .

# Ensure the gradlew script is executable
RUN chmod +x ./gradlew

# Run the Gradle build with caching
RUN ./gradlew :product_module:clean :product_module:build

# Stage 2: Run the application
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copy the built jar from the previous stage
COPY --from=builder /workspace/product_module/build/libs/*.jar app.jar

# Expose port 8081
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
