# Stage 1: Build the application
FROM eclipse-temurin:21 AS builder
WORKDIR /workspace

# Copy the project files
COPY . .

# Change directory to the product_module and build it using the Gradle wrapper
WORKDIR /workspace/product_module

# Gradle build with caching
RUN ../gradlew clean build -x test

# Stage 2: Run the application
FROM eclipse-temurin:21
WORKDIR /app

# Copy the built jar from the previous stage
COPY --from=builder /workspace/product_module/build/libs/*.jar app.jar

# Expose port 8081
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
