spring:
  mvc:
    path_match:
      matching-strategy: ant_path_matcher

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      hikari:
        connection-timeout: 30000 # 30초
        max-lifetime: 1800000 # 30분
        maximum-pool-size: 10
        minimum-idle: 5
        jdbc-url: jdbc:mysql://${DB_HOST_MASTER}:3306/${DB_NAME}
    slave1:
      hikari:
        connection-timeout: 30000 # 30초
        max-lifetime: 1800000 # 30분
        maximum-pool-size: 10
        minimum-idle: 5
        jdbc-url: jdbc:mysql://${DB_HOST_SLAVE1}:3306/${DB_NAME}
    slave2:
      hikari:
        connection-timeout: 30000 # 30초
        max-lifetime: 1800000 # 30분
        maximum-pool-size: 10
        minimum-idle: 5
        jdbc-url: jdbc:mysql://${DB_HOST_SLAVE2}:3306/${DB_NAME}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: ${MONGO_URI}

  rabbitmq:
    host: ${RMQ_HOST}
    port: 5672
    username: ${RMQ_USER}
    password: ${RMQ_PASSWORD}

  #multipart file 기본 설정 1MB
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  batch:
    job:
      enabled: false

jwt:
  secret-key-source: ${SECRET_KEY_SOURCE}

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESSKEY}
      secretKey: ${SECRETKEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true

server:
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, application/json
    min-response-size: 1024
