name: guerilla_commerce

on:
  push:
    branches: [ "main_product" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Create resources directory if missing
        run: |
          mkdir -p product_module/src/main/resources

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.properties
        run: |
          cd /home/runner/work/backend/backend/product_module/src/main/resources
          touch application.properties
          echo "${{ secrets.PRODUCT_MODULE_PROPERTIES }}" > application.properties
        shell: bash

      - name: Build and push Docker images
        run: |
          ./gradlew bootJar -p product_module
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./Dockerfile_Product -t ${{ secrets.DOCKER_USERNAME }}/product_module .
          docker push ${{ secrets.DOCKER_USERNAME }}/product_module

      - name: Execute Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCT_MODULE_HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker stop product_module || true
            docker rm product_module || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/product_module || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/product_module
            docker run -d --name product_module -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/product_module
            docker image prune -f